### ISSUE TITLE
AzureML functions do not display in RStudio when entered in search pane

### ISSUE THREAD

**Issue by Harumafuji** [RevolutionAnalytics/AzureML#101]
Repro:  In RStudio, with AzureML loaded, type in download.datasets in the pane at the top right of the help window (with the magnifying glass icon).  The following will be displayed:

_The search string was "download.datasets"
Help pages:

AzureML::download.datasets		Download one or more datasets from an AzureML workspace._

The hyperlink that appears is also not functional.

However, by typing "?download.datasets" in the console, the help for this function is properly displayed in the help window.  This is the case for other AzureML functions.

**Comment by andrie** [comment]
I don't think this has anything to do with the `AzureML` package.  Try this in a fresh machine (or VM) and you'll notice you can't reproduce.

What you observe is probably an interaction effect from developing the package and RStudio.

Try this:
* In the "packages" tab, click on the AzureML package
* This refreshes the database and then I can search for all functions
