### ISSUE TITLE
New tests in test-2-datasets-upload-download-delete.R take a long time to run

### ISSUE THREAD

**Issue by Harumafuji** [RevolutionAnalytics/AzureML#102]
Originally reported by @andrie; tests were added by Dan (Harumafuji).

**Comment by Harumafuji** [comment]
Changed TSV data source from "MNIST Train 60k 28x28 dense" to "MNIST Test 10k 28x28 dense" in the test_that("Can download .csv and .tsv files", ...).  The latter is 10% the size of the former.

**Comment by andrie** [comment]
Refactored and fixed in #111
