### ISSUE TITLE
minor inconsistency in allowed vals for "filter" param in experiments() function

### ISSUE THREAD

**Issue by georgeAccnt-GH** [RevolutionAnalytics/AzureML#120]
Allowed vals for "filter" param in:
experiments(ws, filter = ...)  
are : “all”, “my datasets”, “samples”

However, the experiments page has "MY EXPERIMENTS" and "SAMPLES" section.  

experiments(ws, filter = "MY EXPERIMENTS") generates an error.

The allowed vals for "filter" param should be: “all”, “my experiments”, “samples”

**Comment by sfweller** [comment]
This now works in the latest version of the azureml package, so the bug can be closed out.
