### ISSUE TITLE
Read workspace data from json file by default

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/azureml#13]
The data is:

```json
{"workspace":{
  "id":"test_id",
  "authorization_token": "test_token",
  "api_endpoint":"api_endpoint",
  "management_endpoint":"management_endpoint"
}}
```

The idea here is that if workspace() is called with no parameters we should try and read `~/.azureml/settings.json` and get the workspace id/authorization token/end points and use the information there.  That way we can keep the tokens out of the notebooks.

**Comment by bwlewis** [comment]
Was added in https://github.com/RevolutionAnalytics/azureml/commit/776a4997ea7ff21ffe843dd81fb91250e1c1a48c
