### ISSUE TITLE
Include geolocation fix identified in AzureML package

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/AzureML#31]
Details at https://github.com/cran/AzureML/pull/1

**Comment by bwlewis** [comment]
There are subtly-different URIs all over the place--see, for example: endpoints, consume, workspace, discoverSchema, publishWebService.  I tried to collect the most commonly used ones in the workspace object, but the API is undocumented and I don't really know what the deal is with all these.

As it stands now, package users can change URIs in every place they are used, so assuming the user understands what these URIs mean, they have control over them.
