### ISSUE TITLE
In callAPI() break immediately for certain types of errors

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/AzureML#47]
Not all errors returned by a 400 response is because the service isn't available.

Sometimes the error code contains helpful debugging information.

In these cases, `callAPI()` should break immediately, rather than retrying several times.

**Comment by bwlewis** [comment]
It's a good point, but the API we're talking to remains unpublished. We don't *really* know what it's going to return to us...

**Comment by andrie** [comment]
I have new information that the error code 503 is used for the situation where the webservice is still initializing. I added the new issue #49 to describe this.
