### ISSUE TITLE
Add mechanism for rate limiting

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/AzureML#49]
As noted in #44, if requests are sent too frequently to the AzureML API, it is very easy to exceed the rate limit.

One possibility is to add multiple retry, possibly with exponential back-off (#48) to all functions that call the API

**Comment by andrie** [comment]
Related to #48

**Comment by andrie** [comment]
Related to #48

**Comment by bwlewis** [comment]
This might be fixed

**Comment by andrie** [comment]
I think this was fixed in #48
