### ISSUE TITLE
Give more descriptive error message when zip isn't available

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/AzureML#53]
User report:

> I’m trying this on Windows… when I try to use publishWebService, I get:

```
Error in publishWebService(ws, fun = add, name = "AzureML-vignette-add",  : 
  Requires external zip utility. Please install zip and try again.
```

> But Windows already has a zip utility, doesn’t It?  I able to zip and unzip files from the File Explorer.  

> I installed http://www.7-zip.org/ but that didn’t work either.  Any ideas what zip utility must be installed and how to make it work?  

---

Since the zip utility should also be in the path, we can make this message more clear and explicit.

**Comment by bwlewis** [comment]
This is a bummer. As far as I can tell (not really documented), AzureML requires .zip flies, and R can only create those using an external program named "zip" that is available in the PATH, see

```r
?zip
```

**Comment by andrie** [comment]
Also add this information to:

* System requirements in DESCRIPTION
* README
* Bug bash instructions
* Vignette
