### ISSUE TITLE
download.intermediate.dataset() not working properly

### ISSUE THREAD

**Issue by lixzhang** [RevolutionAnalytics/AzureML#54]
`download.intermediate.dataset()` returns a dataframe with a single column even though the data has multiple columns

Can you make it so the correct number of columns are returned?

**Comment by andrie** [comment]
The reason that this happens is that the type is incorrectly set to GenericTSV. It should be GenericCSV.

**Comment by bwlewis** [comment]
That's just a bug. It's hard coded in there even though there is an argument for it.

If this can be automatically set it should be.
