### ISSUE TITLE
Can you make the error messages from consume() more informative?

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/AzureML#57]
@lixzhang requested:

> Can you make the error messages from consume() more informative?

> In one case I had the wrong number of columns for the test data, but the error message did not tell me that.

```r
consume(ep, test)
Warning: AzureML http status code: 400
Warning: AzureML error code: LibraryExecutionError
Warning: AzureML error message: Module encountered an internal library error
Error in  consume(ep, test): AzureML returned error code
```

**Comment by andrie** [comment]
@lixzhang

This is all of the information contained in the AzureML requeste response.

As you say, it's not very informative.

Also, since R package has no information about the service itself at runtime, we can't do anything directly in the `consume()` function.

However, one possibility for an improvement is to provide a `validateWebserviceInput() function:

* Use `discoverWebservice()` to query AML for the required input schema
* Then validate that the input data conforms to the service expectation
* If not, throw an error

I don't think we should do this automatically at the start of  every `consume()` call, since this adds communication overhead.

However, we could think about calling this in the event that the server returns this type of error.

**Comment by bwlewis** [comment]
I think this is fixed now
