### ISSUE TITLE
Improve help for download.intermediate.dataset

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/AzureML#60]
Right now the help arguments refer to IDs "obtained from "Generate Data Access Code"

**Comment by bwlewis** [comment]
That's right, you get that precisely from that right-click menu option in the Studio GUI. See the attached screen shot.
![data_access_code](https://cloud.githubusercontent.com/assets/142494/11341504/b6847484-91d0-11e5-846e-ca2670701b7a.png)
