### ISSUE TITLE
workspace() not working properly

### ISSUE THREAD

**Issue by lixzhang** [RevolutionAnalytics/AzureML#74]
I do not have a local settings.json file and am having troubles using the workspace() function. Below is a screenshot of the error messages.

Two questions I have are:
1) Do I have to create a local settings.json file? In version 0.2.4 this file was optional and it worked OK once I provide workspace ID and authorization token.
2) If a local settings.json file is optional, do I have to provide api_endpoint and management_endpoint? In version 0.2.5 I have to provide them and in version 0.2.6 I'm have problems as the screenshot shows.

![issue](https://cloud.githubusercontent.com/assets/9322661/11901257/92a5587e-a578-11e5-9bdd-c2631e54980f.JPG)

**Comment by andrie** [comment]
Thanks for reporting this.

This is a known issue (it surfaced during a bug bash last week that introduced some nasty side-effects.)

We are working on this.  The current dev branch contains some fixes, but I think we still have some niggles to sort out.

Hopefully this will be resolved early next week.

**Comment by andrie** [comment]
This has now been fixed in the dev branch.
