### ISSUE TITLE
Proxy problems

### ISSUE THREAD

**Issue by diandolo** [RevolutionAnalytics/AzureML#91]
Hi, 
I was wondering about solving proxy problems in R. I tried with RCurlOptions() but it doesn't work, however I noted that the package is based on Curl.
Can you suggest other methods? 

Thank you.
Daniele

**Comment by andrie** [comment]
I don't think your question has anything to do with the `AzureML` package.

A quick google search for `[R] curl proxy` leads to this page, among others:

http://stackoverflow.com/questions/6467277/proxy-setting-for-r

**Comment by diandolo** [comment]
Of course you are right. However I told you that I already tried with 'RCurl methods' .
Free to close/cancel the issue, I'll search on Google.
Thank you for the answer.
Daniele

**Comment by andrie** [comment]
Good luck!

If you discover that we have to modify the `AzureML` package to resolve your issue, please post a new issue!

Andrie

**Comment by bwlewis** [comment]
Just FYI, note that the package depends on the new 'curl' package for R, *not* RCurl, which I think you are referring to. See
