### ISSUE TITLE
Cases 2 and 3 do not work in examples for download.datasets(.) in the help file

### ISSUE THREAD

**Issue by Harumafuji** [RevolutionAnalytics/AzureML#95]
Get the following error:

 Error in as.data.frame.default(datasets) : 
  cannot coerce class ""function"" to a data.frame

**Comment by andrie** [comment]
Can you please paste the offending code here?

**Comment by Harumafuji** [comment]
In these two cases in the examples in the help file for download.datasets(.):

frame2 <- download.datasets(datasets(ws), name)                # case 2
frame3 <- download.datasets(subset(d, Name == name))      # case 3,

we get the following error (as above):
Error in as.data.frame.default(datasets) : 
cannot coerce class ""function"" to a data.frame

The offending code is in the function definition in datasets.R; viz,
  # Coerce to data frame, if for example presented as a list.
  if(is.null(dim(datasets))) datasets = as.data.frame(datasets(dataset))

The problem seems to be that the argument dataset here, in case 2, is set to datasets(ws), so the actual function call taking place would be datasets(datasets(ws)), but the datasets(.) function is expecting a workspace object for the argument.

Similarly, for case 3, the function call would be
datasets(subset(d, Name == name)).

In neither case is the argument a workspace object.

**Comment by Harumafuji** [comment]
Hit the wrong button -- reopened issue.

**Comment by Harumafuji** [comment]
This issue has been mostly fixed, although one last bug remains, which is detailed in a new issue: #100.  Will close this issue.

**Comment by andrie** [comment]
Fixed in #111
