### ISSUE TITLE
In publishWebService, outputSchema cannot be specified as a dataframe

### ISSUE THREAD

**Issue by peterandrien** [RevolutionAnalytics/AzureML#99]
When the inputSchema is a dataframe the outputSchema will default to a dataframe with the same schema, however you cannot specify a dataframe (either the same or different) as the outputSchema.

```
ep <- publishWebService(ws,
                        fun = function(x) {return(x)},
                        name = "test",
                        inputSchema = mtcars,
                        outputSchema = mtcars)

```

Running the above example gives:

```
Error in azureSchema(outputSchema) : 
  Error: data type "21" not supportedError: data type "21" not supportedError: data type "22.8" not supportedError: data type "21.4" not supportedError: data type "18.7" not supportedError: data type "18.1" not supportedError: data type "14.3" not supportedError: data type "24.4" not supportedError: data type "22.8" not supportedError: data type "19.2" not supportedError: data type "17.8" not supportedError: data type "16.4" not supportedError: data type "17.3" not supportedError: data type "15.2" not supportedError: data type "10.4" not supportedError: data type "10.4" not supportedError: data type "14.7" not supportedError: data type "32.4" not supportedError: data type "30.4" not supportedError: data type "33.9" not supportedError: data type "21.5" not supportedError: data type "15.5" not supportedError: data type "15.2" not supportedError: data type "13.3" not supportedError: data type "19.2" not supportedError: data type "27.3" not supportedError: data type "26" not suppor
```

**Comment by bwlewis** [comment]
I'm not sure that's quite right. The doc does not say that when `inputSchema` is a data.frame the output will default to a data.frame with the same schema.

Instead what I think happens is that the output (from the R function that defines the service) is assumed to be a data.frame generically, and the `outputSchema` in that case is implicitly defined by that function output (that is, it can and generally will be different than the `inputSchema`).

As indicated in the doc, you can override the output schema types by providing an explicit list of types. But as indicated in the doc, outputSchema only accepts a list.

Perhaps we need to add more to the doc to make this more clear?

**Comment by sfweller** [comment]
It looks like Peter's above example works, if you use the default settings as described in the help file for the 'publishWebService()' function, eg if you only specify the 'inputSchema' argument and leave the 'outputSchema' argument blank:

> ep <- publishWebService(ws,
+ fun = function(x) {return(x)},
+ name = "test",
+ inputSchema = mtcars)

It seems to me however that it should also work if the 'ouputShema' argument is supplied...
What do you think Brian?
